name: Build and Test

on:
  push:
    branches:
      - master  # or use your desired branch name

jobs:
  test:
    runs-on: self-hosted  # Use 'ubuntu-latest' for GitHub-hosted runners, or your self-hosted runner.

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java (since you're using TestNG and Cucumber, you need Java installed)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      # Install dependencies (assuming Maven)
      - name: Install dependencies
        run: mvn clean install  # Or use './gradlew build' if you are using Gradle

      # Run the tests (this will run Cucumber with TestNG)
      - name: Run Cucumber with TestNG
        run: mvn test  # Adjust this if you're using a different build tool (e.g., Gradle)


